name: Bug
description: Report an issue to help improve the project.
labels: "bug"
title: '[BUG] <description>'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Which version of Manim Slides are you using? You can use `manim-slides --version` to get that information.
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: What is your platform. Linux, macOS, or Windows?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
