name: Upload Packages

on:
  push:

  release:
    types: [published]

jobs:
  publish-python:
    name: Publish Python package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rye
      env:
        RYE_INSTALL_OPTION: --yes
      run: |
        curl -sSf https://rye-up.com/get | bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Configure Rye
      run: rye config --set-bool behavior.use-uv=true

    - name: Build package
      run: rye build

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Version
      id: create_release
      shell: python
      env:
        tag_act: ${{ github.ref }}
      run: |
        import os
        ref_tag = os.getenv('tag_act').split('/')[-1]
        with open(os.getenv('GITHUB_OUTPUT'), 'w') as f:
          print(f"tag_name={ref_tag}", file=f)

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64,linux/amd64
        file: docker/Dockerfile
        push: true
        tags: |
          ghcr.io/jeertmans/manim-slides:latest
          ghcr.io/jeertmans/manim-slides:${{ steps.create_release.outputs.tag_name }}
